name: build-grades
on:
  workflow_dispatch:          # اجرای دستی
  push:
    paths:
      - build_grades_split.py
      - .github/workflows/build-grades.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script – generate JSON files
        run: python build_grades_split.py

      - name: Commit & push JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated: refresh grades JSON"
            git push
          fi
